backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: img

collections:
  - name: "Frontpage"
    label: "Etusivu"
    files:
    - label: "Osa 1"
      name: "part1"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Items'
          name: "items"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}


# FLOU - the company
  - name: "FLOU"
    label: "FLOU"
    files:
    - label: "FLOU"
      name: "flou"
      file: "content/flou.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Kuvaus'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - { label: "Sisällön kuva", name: "bodyIMG", widget: "image", required: true}
        - label: 'Historia'
          name: "timeline"
          widget: list
          fields:
          - { label: "Vuosiluku", name: "year", widget: "number"}
          - label: 'Vuoden kuvaus'
            name: 'yeardescription'
            widget: 'object'
            fields:
            - { label: "Suomeksi", name: "fi", widget: "string"}
            - { label: "In English", name: "en", widget: "string"}
          - label: 'Tapahtumat'
            name: "events"
            widget: list
            fields:
            - label: 'Tapahtuma'
              name: 'event'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}


# Competences/skillset
  - name: "Competences"
    label: "Osaaminen"
    files:
    - label: "Osaaminen - sivun sisältö"
      name: "pagecontent"
      file: "content/competence_content.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Lyhyt yleisesittely'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
    - label: "Osaaminen - osa-alueet"
      name: "sections"
      file: "content/competences_list.md"
      fields:
        - label: 'Osaamisaluelistaus'
          name: "category"
          widget: list
          fields:
            - label: 'Otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - {label: "url - lyhyt ja ei välejä", name: "url", widget: "string"}
            - { label: "Osaamisalueen kuva", name: "skillIMG", widget: "image", required: true}
            - label: 'Lyhyt kuvaus'
              name: 'short'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - label: 'Pitkä kuvaus'
              name: 'long'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "markdown"}
              - { label: "In English", name: "en", widget: "markdown"}
            - label: 'Alakategoriat'
              name: "subcategories"
              widget: list
              fields:
                - label: 'Otsikko'
                  name: 'title'
                  widget: 'object'
                  fields:
                  - { label: "Suomeksi", name: "fi", widget: "string"}
                  - { label: "In English", name: "en", widget: "string"}
                - label: 'Kuvaus'
                  name: 'description'
                  widget: 'object'
                  fields:
                  - { label: "Suomeksi", name: "fi", widget: "text"}
                  - { label: "In English", name: "en", widget: "text"}
                - label: 'Esimerkkiprojektit'
                  name: 'projects'
                  widget: 'list'
                  fields:
                  - label: 'Otsikko'
                    name: 'title'
                    widget: 'object'
                    fields:
                    - { label: "Suomeksi", name: "fi", widget: "string"}
                    - { label: "In English", name: "en", widget: "string"}
                  - { label: "Osaamisalueen kuva", name: "skillIMG", widget: "image", required: true}
                  - label: 'Kuvaus'
                    name: 'description'
                    widget: 'object'
                    fields:
                    - { label: "Suomeksi", name: "fi", widget: "text"}
                    - { label: "In English", name: "en", widget: "text"}
    - label: "Osaaminen - Projektireferenssit"
      name: "refs"
      file: "content/competences_refs.md"
      fields:
        - label: 'Referenssiprojektit'
          name: "refs"
          widget: list
          fields:
            - label: 'Otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Kuva", name: "skillIMG", widget: "image", required: true}
            - label: 'Lyhyt kuvaus'
              name: 'short'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - label: 'Asiakas'
              name: 'customer'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - label: 'Specialist'
              name: 'specialist'
              widget: 'relation'
              collection: 'tiimi'
              searchFields: ['persons']
              valueField: 'persons.*.email'
              displayFields: ['persons.*.name']


# the team
  - name: "Team"
    label: "Tiimi"
    files:
    - label: "Tiimi"
      name: "tiimi"
      file: "content/tiimi.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'FLOUlaiset'
          name: "persons"
          widget: list
          fields:
            - { label: "Nimi", name: "name", widget: "string", required: true}
            - label: 'Titteli'
              name: 'role'
              required: true
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Sähköposti", required: true, name: "email", widget: "string"}
            - { label: "Puhelin", name: "phone", required: true, widget: "string"}
            - label: 'Osaamisalueet (yksi per listaelementti)'
              name: 'skills'
              widget: 'list'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - label: 'Lyhyt kuvaus'
              name: "description"
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - { label: "Kuva", name: "profileIMG", widget: "image", required: true}


# the blog
  - name: "Blog"
    label: "Blogi"
    files:
    - label: "Blogit"
      name: "blogs"
      file: "content/blogs.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - label: 'Kuvaus'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Blogit'
          name: 'blogs'
          widget: 'list'
          fields:
            - {label: "url - lyhyt ja ei välejä", name: "url", widget: "string"}
            - label: 'Blogin otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Publish Date", name: "date", widget: "datetime" }
            - { label: "Blogin kuva", name: "img", widget: "image", required: true}
            - label: 'Lyhyt kuvaus (max. 2 lausetta)'
              name: 'short'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - label: 'Pitkä blogiteksti'
              name: 'long'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "markdown"}
              - { label: "In English", name: "en", widget: "markdown"}
            - label: 'Mukana tekemässä (anna sähköpostioisoite)'
              name: "email"
              widget: list
              fields:
                - { label: "email", name: "name", widget: "string"}
                - label: 'Rooli'
                  name: 'role'
                  widget: 'object'
                  fields:
                  - { label: "Suomeksi", name: "fi", widget: "string"}
                  - { label: "In English", name: "en", widget: "string"}


# contact site content DONE
  - name: "Contact"
    label: "Ota yhteyttä"
    files:
    - label: "Header"
      name: "header"
      file: "content/contact.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Leipateksti'
          name: 'bodyObject'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - { label: "Täyttökuva", name: "fillIMG", widget: "image", required: true}

# FLOU - the company
  - name: "Jobs"
    label: "Avoimet työpaikat"
    files:
    - label: "Kuvaus"
      name: "description"
      file: "content/job_description.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Infoteksti'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - label: 'Kontakti'
          name: 'contact'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
    - label: "Avoimet työpaikat"
      name: "openings"
      file: "content/job_openings.md"
      fields:
        - label: 'Avoimet haut'
          name: 'openings'
          widget: 'list'
          fields:
            - label: 'Otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Publish Date", name: "publishdate", widget: "datetime" }
            - label: 'Hakuaika'
              name: 'timeperiod'
              widget: 'object'
              fields:
              - { label: "Alkuaika", name: "starttime", widget: "date"}
              - { label: "Loppuaika", name: "endtime", widget: "date", required: false}
            - label: 'Kuvaus'
              name: 'description'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "markdown"}
              - { label: "In English", name: "en", widget: "markdown"}