backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: img

collections:
  - name: "Frontpage"
    label: "Etusivu"
    files:
    - label: "Osa 1"
      name: "part1"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Items'
          name: "items"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}


# FLOU - the company
  - name: "FLOU"
    label: "FLOU"
    files:
    - label: "FLOU"
      name: "flou"
      file: "content/flou.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Kuvaus'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - { label: "Sisällön kuva", name: "bodyIMG", widget: "image", required: true}
        - label: 'Historia'
          name: "timetile"
          widget: list
          fields:
          - { label: "Vuosiluku", name: "year", widget: "number"}
                  - label: 'Vuoden kuvaus'
                    name: 'yeardescription'
                    widget: 'object'
                    fields:
                    - { label: "Suomeksi", name: "fi", widget: "string"}
                    - { label: "In English", name: "en", widget: "string"}
                  - label: 'Tapahtumat'
                    name: "events"
                    widget: list
                    fields:
                      - label: 'Tapahtuma'
                            name: 'event'
                            widget: 'object'
                            fields:
                            - { label: "Suomeksi", name: "fi", widget: "string"}
                            - { label: "In English", name: "en", widget: "string"}


# Competences/skillset
  - name: "Competences"
    label: "Osaaminen"
    files:
    - label: "Osaaminen - sivu"
      name: "part1"
      file: "content/competences.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Lyhyt yleisesittely'
          name: 'description'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - label: 'Osaamisaluelistaus'
          name: "items"
          widget: list
          fields:
            - {label: "url - lyhyt ja ei välejä", name: "url", widget: "string"}
            - { label: "Osaamisalueen kuva", name: "skillIMG", widget: "image", required: true}
            - label: 'Otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - label: 'Lyhyt kuvaus'
              name: 'short'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - label: 'Pitkä kuvaus'
              name: 'long'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "markdown"}
              - { label: "In English", name: "en", widget: "markdown"}


# the team
  - name: "Team"
    label: "Tiimi"
    files:
    - label: "Tiimi"
      name: "tiimi"
      file: "content/tiimi.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'FLOUlaiset'
          name: "persons"
          widget: list
          fields:
            - { label: "Nimi", name: "name", widget: "string", required: true}
            - label: 'Titteli'
              name: 'role'
              required: true
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Sähköposti", required: true, name: "email", widget: "string"}
            - { label: "Puhelin", name: "phone", required: true, widget: "string"}
            - label: 'Osaamisalueet (yksi per listaelementti)'
              name: 'skills'
              widget: 'list'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - label: 'Lyhyt kuvaus'
              name: "description"
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - { label: "Kuva", name: "profileIMG", widget: "image", required: true}


# the blog
  - name: "Blog"
    label: "Blogi"
    files:
    - label: "Blogit"
      name: "blogs"
      file: "content/blogs.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Blogit'
          name: 'blogs'
          widget: 'list'
          fields:
            - {label: "url - lyhyt ja ei välejä", name: "url", widget: "string"}
            - label: 'Blogin otsikko'
              name: 'title'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "string"}
              - { label: "In English", name: "en", widget: "string"}
            - { label: "Publish Date", name: "date", widget: "datetime" }
            - { label: "Blogin kuva", name: "img", widget: "image", required: true}
            - label: 'Lyhyt kuvaus (max. 2 lausetta)'
              name: 'short'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "text"}
              - { label: "In English", name: "en", widget: "text"}
            - label: 'Pitkä blogiteksti'
              name: 'long'
              widget: 'object'
              fields:
              - { label: "Suomeksi", name: "fi", widget: "markdown"}
              - { label: "In English", name: "en", widget: "markdown"}
            - label: 'Mukana tekemässä (anna sähköpostioisoite)'
              name: "email"
              widget: list
              fields:
                - { label: "email", name: "name", widget: "string"}


# contact site content DONE
  - name: "Contact"
    label: "Ota yhteyttä"
    files:
    - label: "Header"
      name: "header"
      file: "content/contact.md"
      fields:
        - label: 'Otsikko'
          name: 'title'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "string"}
          - { label: "In English", name: "en", widget: "string"}
        - { label: "Headerin kuva", name: "headerIMG", widget: "image", required: true}
        - label: 'Leipateksti'
          name: 'bodyObject'
          widget: 'object'
          fields:
          - { label: "Suomeksi", name: "fi", widget: "markdown"}
          - { label: "In English", name: "en", widget: "markdown"}
        - { label: "Täyttökuva", name: "fillIMG", widget: "image", required: true}